GET http://localhost:8080/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbmF0dGYiLCJpYXQiOjE3MTg3MDI3NTQsImV4cCI6MTcxODc4OTE1NH0.VozMBySInAiNfQdRFmUEP2zPP8zndzMMKUu0pIyRJlw