##todo: nahrání na náš server
#
#name: CICD
#
#on:
#  push:
#    branches: [ main ]
#
#  workflow_dispatch:
#
#env:
#  # Postgres
#  POSTGRESQL_VERSION: 15.1
#  POSTGRESQL_DB: postgres
#  POSTGRESQL_USER: postgres
#  POSTGRESQL_PASSWORD: postgres
#  # Java
#  JAVA_VERSION: 19
#  # DockerHub
#  DOCKER_HUB_USERNAME: mckillem
#  # AWS & Elastic Bean Stalk
##  AWS_REGION: eu-central-1
##  EB_ENVIRONMENT_NAME: Springbootreactfullstack-env
##  EB_APPLICATION_NAME: springboot-react-fullstack
##  EB_DEPLOYMENT_PACKAGE: elasticbeanstalk/docker-compose.yml
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:15
#        env:
#          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
#          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
#          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
#        ports:
#          - 5432:5432
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Setup Java JDK
#        uses: actions/setup-java@v1.4.3
#        with:
#          java-version: ${{ env.JAVA_VERSION }}
#
#      - name: Build Number
#        id: build-number
#        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"
#
#      - name: Docker Login
#        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
#        with:
#          username: ${{ env.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#
#      - name: Maven Clean Package and Push to Dockerhub
#        run: |
#          ./mvnw --no-transfer-progress clean package \
#            -P build-frontend \
#            -P jib-push-to-dockerhub \
#              -Dapp.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}}
#
#      - name: Update and commit app version in docker-compose.yaml
#        run: |
#          BUILD_NUMBER=${{steps.build-number.outputs.BUILD_NUMBER}}
#          echo -e "Current elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
#          sed -i -E 's_(mckillem/todo:)([^"]*)_\1'${BUILD_NUMBER}'_' elasticbeanstalk/docker-compose.yml
#          echo -e "Current elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add elasticbeanstalk/docker-compose.yml
#          git commit -m "new app version: ${BUILD_NUMBER}"
#          git push
